#!/usr/bin/env bash
# Run `moon prove` on a proof sub-package with the multi-solver config
# generated by proofs/setup.sh.
#
# Usage:
#   bash proofs/prove.sh                 # prove every wrap package + proofs/
#   bash proofs/prove.sh <pkg>           # one package, e.g. aead/wrap
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONF="$REPO_ROOT/proofs/why3.conf"

if [ ! -f "$CONF" ]; then
  echo "[proofs/prove.sh] $CONF missing; run: bash proofs/setup.sh" >&2
  exit 1
fi

# When invoked inside `nix develop`, MOON_HOME points at the nix-bundled
# moonbit-core which doesn't carry moonbitlang/x. Fall back to the user's
# ~/.moon registry so the workspace resolves.
unset MOON_HOME

prove_one() {
  local pkg="$1"
  echo "=== $pkg ==="
  (cd "$REPO_ROOT/$pkg" && moon prove --why3-config "$CONF" 2>&1 \
     | grep -E '(Succeeded|Failed|Summary|proved|failure|timeout)' | head -4)
}

if [ $# -eq 0 ]; then
  for pkg in proofs pem/wrap aead/wrap hkdf/wrap asn1/wrap pbkdf2/wrap bip32/wrap bip39/wrap hash/wrap totp/wrap scrypt/wrap getrandom/wrap argon2/wrap jwt/wrap; do
    prove_one "$pkg"
  done
else
  prove_one "$1"
fi
